name: Quality Check

on:
  push:
    branches: [ "trunk" ]
  pull_request:
    branches: [ "trunk" ]
    
  workflow_dispatch:
jobs:
  build:
    uses: ddi1225-h2040/DevOpsReusableWorkflows/.github/workflows/quality-check.yml@trunk
    secrets: inherit
