name: Dependency Review

on:
  pull_request:

jobs:
  dependency-review:
    name: Run Dependency Review
    runs-on: ubuntu-latest
    
    steps:
      # Step to check out the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step to perform the dependency review
      - name: Dependency Review
        uses: actions/dependency-review-action@v4.3.4
